name: Build Codex for Android (HTTP/1.1)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      - name: Configure linker
        run: |
          echo "CC_aarch64_linux_android=$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang" >> $GITHUB_ENV
          echo "CXX_aarch64_linux_android=$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++" >> $GITHUB_ENV
          echo "AR_aarch64_linux_android=$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" >> $GITHUB_ENV
          echo "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang" >> $GITHUB_ENV

      # --- PATCH: paksa semua reqwest builder pakai HTTP/1.1 ---
      - name: Patch reqwest to force HTTP/1.1
        run: |
          sed -i -E 's#reqwest::Client::builder\(\)\s*\.\s*build\(\)#reqwest::Client::builder().http1_only(true).build()#g' backend-client/src/client.rs || true
          sed -i -E 's#reqwest::Client::builder\(\)\s*\.\s*build\(\)#reqwest::Client::builder().http1_only(true).build()#g' cloud-tasks/src/env_detect.rs || true
          sed -i -E 's#(let\s+mut\s+builder\s*=\s*reqwest::Client::builder\(\))\s*;#\1.http1_only(true);#' core/src/default_client.rs || true
          sed -i -E 's#Client::builder\(\)#Client::builder().http1_only(true)#g' responses-api-proxy/src/lib.rs || true

          echo "Patched reqwest builders to force HTTP/1.1"

      - name: Build codex CLI (Android bionic)
        run: cargo build --release -p codex-cli --target aarch64-linux-android

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: codex-android-http1
          path: target/aarch64-linux-android/release/codex
