name: Build Codex

on:
  workflow_dispatch: {}

concurrency:
  group: android-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      RUSTFLAGS: "-C debuginfo=0"

    steps:
      - uses: actions/checkout@v4

      # Rust + target Android (arm64)
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      # Android NDK (linker bionic)
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      - name: Configure Android linker (bionic)
        run: |
          echo "CC_aarch64_linux_android=$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang" >> $GITHUB_ENV
          echo "CXX_aarch64_linux_android=$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++" >> $GITHUB_ENV
          echo "AR_aarch64_linux_android=$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" >> $GITHUB_ENV
          echo "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang" >> $GITHUB_ENV

      # (OPSIONAL) Matikan HTTP/2 di semua reqwest client yang dipakai CLI
      - name: Force HTTP/1.1 (disable H2) [optional]
        working-directory: codex-rs
        run: |
          sed -i -E 's#reqwest::Client::builder\(\)\s*\.\s*build\(\)#reqwest::Client::builder().http1_only(true).build()#g' backend-client/src/client.rs || true
          sed -i -E 's#reqwest::Client::builder\(\)\s*\.\s*build\(\)#reqwest::Client::builder().http1_only(true).build()#g' cloud-tasks/src/env_detect.rs || true
          sed -i -E 's#(let\s+mut\s+builder\s*=\s*reqwest::Client::builder\(\))\s*;#\1.http1_only(true);#' core/src/default_client.rs || true
          sed -i -E 's#Client::builder\(\)#Client::builder().http1_only(true)#g' responses-api-proxy/src/lib.rs || true

      # Build paket CLI dari workspace (binari 'codex')
      - name: Build codex CLI (Android)
        working-directory: codex-rs
        run: |
          rustup target add aarch64-linux-android
          cargo build --release --target aarch64-linux-android -p codex-cli 2>&1 | tee ../build-android.log
          echo "== target output =="
          ls -lah target/aarch64-linux-android/release || true

      # Upload log selalu (buat debug kalau gagal)
      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-android-log
          path: build-android.log

      # Upload binari (nama normalnya 'codex'); kalau beda, fallback cari otomatis
      - name: Upload codex binary (exact)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: codex-android-http1
          path: codex-rs/target/aarch64-linux-android/release/codex

      - name: Upload codex binary (fallback glob)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: codex-android-http1-glob
          path: |
            codex-rs/target/aarch64-linux-android/release/codex*
            !**/*.d
            !**/*.rlib
            !**/*.rmeta
            !**/*.so
